update: add constitution
zafuacm/wiki pull request #40
Opened 2023-07-19 06:29 UTC by smlwang

添加集训队章程

2023-07-19 11:05 UTC, rogeryoungh commented on docs/about/constitution.md
> +**第二条** 集训队队员入队为申请制，学生在获取入队资格后申请入队。入队资格主要通过写入队题单获得，除此之外还可通过在校内正式比赛（如新生赛、校赛、选拔赛）中取得二等奖及以上奖项获得。
join-us 那一节也补充一下。

2023-07-19 13:28 UTC, rogeryoungh commented
1. 你的代码包含冲突，请解决。
2. 请 resolve 已解决的问题，我才能 review。

2023-07-19 13:53 UTC, smlwang commented
已解决冲突
已 resolve

2023-07-20 00:26 UTC, rogeryoungh commented
我不记得atcoder分可以进队。

2023-07-20 01:16 UTC, rogeryoungh commented on docs/about/join-us.md
> +入队为申请制，为减少工作量不再设置面试，但仍需提交申请邮件。新队员入队后将挑时间召集新队员开会，讲解一些常识。
没必要说不再设置面试。面试除了在我们的讨论中出现，并没有公开通知过。

2023-07-20 03:11 UTC, rogeryoungh commented on docs/about/join-us.md
> +3. 写完[入门题单](https://vjudge.net/article/3299)（男生 150 题，女生 120 题）。
只保留这一条，添加到规章的链接。

2023-07-20 03:11 UTC, rogeryoungh commented on docs/about/constitution.md
> +3. 写完[入门题单](https://vjudge.net/article/3299)男生 150 题，女生 120 题）。
括号不对。

2023-07-20 04:12 UTC, rogeryoungh commented on docs/about/join-us.md
> +对于大一同学，我们推荐写入门题单获取入队资格。非大一同学除入门题单外还需满足一个条件，具体说明见 [集训队章程队员选拔章节](./constitution.md##第二章-队员选拔)。
大二要求写 200 到 250 题吧。要求校赛获奖有点难度。

2023-07-20 09:23 UTC, smlwang commented on docs/about/join-us.md
> +对于大一同学，我们推荐写入门题单获取入队资格。非大一同学除入门题单外还需满足一个条件，具体说明见 [集训队章程队员选拔章节](./constitution.md##第二章-队员选拔)。
大二还需要分男女吗，目前分了男 200， 女 170.

2023-07-20 14:20 UTC, rogeryoungh requested changes

2023-07-20 14:20 UTC, rogeryoungh commented on docs/about/constitution.md
> +3. 写完[入门题单](https://vjudge.net/article/3299)。
大一大二统一题量要求。

2023-07-20 15:33 UTC, rogeryoungh commented on docs/about/join-us.md
> +    3. Atcoder 用户名：xxx。
atcoder 这里没删。

2023-07-20 15:33 UTC, rogeryoungh commented on docs/about/join-us.md
> +我们推荐写入门题单获取入队资格，其他获取方式见 [集训队章程队员选拔章节](./constitution.md##第二章-队员选拔)。
id定位是单个井号。

2023-07-20 16:20 UTC, merged